---
all:
  children:
    linux_servers:
      hosts:
        #dev_server:
        #  ansible_host: 192.168.1.100
        #  ansible_user: ubuntu
        #  ansible_port: 22
        #test_server:
        #  ansible_host: 192.168.1.101
        #  ansible_user: ubuntu
        #  ansible_port: 22
        prod_server:
          ansible_host: lixiarchos.site
          ansible_user: root
          ansible_port: 22
      vars:
        ansible_python_interpreter: /usr/bin/python3
        # Optional: SSH key authentication
        # ansible_ssh_private_key_file: ~/.ssh/id_rsa

