package com.web.Lixiarchos.enums;

/* ALWAYS ADD NEW VALUES TO THE END OF THE LIST OTHERWISE DATA IN DB WON'T MATCH TO ORDER SINCE IT USES IDs*/
public enum Religion {

    CHRISTIAN_ORTHODOX,
    AGNOSTICIST,
    ATHEIST,
    CHRISTIAN_CATHOLIC,
    MUSLIM,
    OTHER

}
